#!/bin/bash
set -x
cd ${OPENSHIFT_DATA_DIR}/github/openshift/app01
bash install_step2.sh
bash install_step3.sh
bash install_step4.sh
bash install_step5.sh
bash install_step6.sh
bash install_step7.sh
bash install_step8.sh
bash install_step9.sh
bash install_step10.sh
bash install_step11.sh
bash install_step12.sh
bash install_step13.sh
bash install_step14.sh
bash install_step15.sh
bash install_step16.sh
bash install_step17.sh
bash install_step18.sh
