default:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: smtp.mail.yahoo.co.jp
      port: 587
      domain: yahoo.co.jp
      authentication: :plain
      user_name: "__USER_NAME__" 
      password: "__PASSWORD__"
