#!/bin/bash

set -x

export TZ=JST-9

cd /tmp
wget http://samba.org/ftp/ccache/ccache-3.2.1.tar.xz
tar Jxf  ccache-3.2.1.tar.xz
cd ccache-3.2.1
./configure --prefix=${OPENSHIFT_DATA_DIR}/ccache
time make -j4
make install

export PATH="${OPENSHIFT_DATA_DIR}/ccache/bin:$PATH"

mkdir /tmp/ccache
mkdir /tmp/tmp_ccache
export CCACHE_DIR=/tmp/ccache
export CCACHE_TEMPDIR=/tmp/tmp_ccache
export CCACHE_LOGFILE=${OPENSHIFT_LOG_DIR}/ccache.log
export CCACHE_MAXSIZE=500M
export PATH="${OPENSHIFT_DATA_DIR}/ccache/bin:$PATH"

cd /tmp
wget http://www.delegate.org/anonftp/DeleGate/delegate9.9.13.tar.gz
tar xfz delegate9.9.13.tar.gz
cd delegate9.9.13
# CC="ccache gcc" \
# CFLAGS="-O2 -march=native -pipe -fomit-frame-pointer -s" \
# CXXFLAGS="-O2 -march=native -pipe" \
# time make -j4
time make -j4 CC="ccache gcc"
